# Generated by Django 4.2.11 on 2024-03-26 20:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "data_pedido",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=200)),
                ("endereco", models.CharField(blank=True, max_length=200, null=True)),
                ("cidade", models.CharField(max_length=200)),
                ("estado", models.CharField(max_length=200)),
                (
                    "data_cadastro",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("telefone", models.CharField(max_length=200)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_produto",
                    models.CharField(default="Produto sem nome", max_length=200),
                ),
                ("slug", models.SlugField(default="", max_length=200)),
                ("descricao", models.TextField()),
                ("quantidade", models.IntegerField(default=0)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="")),
                ("preco", models.DecimalField(decimal_places=2, max_digits=5)),
                ("visualizacao", models.IntegerField(default=0)),
                (
                    "data_produto",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordenando_por", models.CharField(max_length=200)),
                ("endereco_envio", models.CharField(max_length=200)),
                ("subtotal", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                (
                    "data_pedido",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("telefone", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                (
                    "pedido_status",
                    models.CharField(
                        choices=[
                            ("Pedido Recebido", "Pedido Recebido"),
                            ("Pedido em Processamento", "Pedido em Processamento"),
                            ("Pedido Enviado", "Pedido Enviado"),
                            ("Pedido Entregue", "Pedido Entregue"),
                            ("Pedido Cancelado", "Pedido Cancelado"),
                        ],
                        default="Pedido Recebido",
                        max_length=200,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "carrinho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.carrinho",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarrinhoProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=5)),
                ("avaliacao", models.PositiveIntegerField()),
                ("subtotal", models.PositiveIntegerField()),
                (
                    "data_pedido",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "carrinho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.carrinho",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.produto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="carrinho",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projeto.cliente"
            ),
        ),
    ]
